#!/usr/bin/env bash

session_name="$1"

if [[ -z "$session_name" ]]; then
    exit 0
fi

current_session="$(tmux display-message -p '#S')"

if [[ "$session_name" == "$current_session" ]]; then
    tmux display-message "Cannot delete current session: $session_name"
    exit 0
fi

tmux kill-session -t "$session_name"
