#!/usr/bin/env bash

session="${1:-$(tmux display-message -p '#{session_name}')}"

tmux list-windows -t "$session" \
    -F '#{?window_active,>, }|#{window_index}|#{pane_current_command}|#{window_panes}' |
    awk -F'|' '{
      printf "%s  %-2s %-14s [%s]\n",
             $1, $2, $3, $4
    }'
