#!/usr/bin/env bash

selected=$(
    find "$HOME" -mindepth 1 -maxdepth 4 \
        \( -name "node_modules" -o -name ".git" -o -name "target" \) -prune -o \
        -type d -print |
        fzf --reverse --prompt="✦ ❯ " --header="━━━━━━━━━━━━━━━ ✦ SESSIONIZER ✦ ━━━━━━━━━━━━━━━" \
            --header-first \
            --color="header:italic" \
            --ignore-case \
            --wrap \
            --info=hidden \
            --input-border=rounded \
            --preview='tree -C -L 3 {}' \
            --preview-border=rounded \
            --preview-window=right:50%:wrap
)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$selected_name"
    exit 0
else
    tmux switch-client -t "$selected_name"
fi
