#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

selected_session=$(
    bash "$script_dir/session-list" |
        fzf --reverse \
            --prompt="-> " \
            --header="━━━━━━━━━━━━━━━ ✦ SESSION-SWITCHER ✦ ━━━━━━━━━━━━━━━ | Ctrl-O: new | Ctrl-D: delete" \
            --header-first \
            --ignore-case \
            --delimiter='\t' \
            --with-nth=4 \
            --color="header:italic" \
            --border=rounded \
            --info=hidden \
            --input-border=rounded \
            --preview-border=rounded \
            --preview-window=right:50%:wrap \
            --preview="tmux list-windows -t {1}" \
            --bind="ctrl-o:become(bash '$script_dir/sessionizer')" \
            --bind="ctrl-d:execute-silent(bash '$script_dir/delete-session' {1})+reload(bash '$script_dir/session-list')" \
            --layout=reverse |
        awk -F'\t' '{print $1}'
)

if [[ -z $selected_session ]]; then
    exit 0
fi

if [[ -n "$selected_session" ]]; then
    tmux switch-client -t "$selected_session"
fi
