#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

switcher_key="$(tmux show-option -gqv "@session_switcher_key")"
creator_key="$(tmux show-option -gqv "@session_create_key")"

switcher_key="${switcher_key:-s}"
creator_key="${creator_key:-j}"

selected_session=$(
    bash "$script_dir/session-list" |
        fzf --reverse \
            --ignore-case \
            --delimiter='\t' \
            --with-nth=2 \
            --color="header:italic,border:#908caa,pointer:#9ccfd8,marker:#eb6f92" \
            --border=rounded \
            --info=hidden \
            --input-border=none \
            --preview-border=left \
            --preview-window=right:50% \
            --preview="bash '$script_dir/session-preview' {1}" \
            --bind="ctrl-i:become(bash '$script_dir/sessionizer')" \
            --bind="ctrl-d:execute-silent(bash '$script_dir/delete-session' {1})+reload(bash '$script_dir/session-list')" \
            --bind="ctrl-l:execute-silent(tmux select-window -t {1} -n)+refresh-preview" \
            --bind="ctrl-h:execute-silent(tmux select-window -t {1} -p)+refresh-preview" \
            --layout=reverse |
        awk -F'\t' '{print $1}'
)

if [[ -z $selected_session ]]; then
    exit 0
fi

if [[ -n "$selected_session" ]]; then
    tmux switch-client -t "$selected_session"
fi
