#!/usr/bin/env bash

current_session=$(tmux display-message -p '#S')

selected_session=$(
    tmux list-sessions -F "#{session_name}|#{session_windows}|#{?session_attached,attached,detached}" |
        awk -F'|' -v current="$current_session" '
            {
                marker = ($1 == current) ? "*" : " "
                printf "%s\t%s\t%s\t%s %-24s %3s windows (%s)\n", $1, $2, $3, marker, $1, $2, $3
            }
        ' |
        fzf --reverse \
            --prompt="-> " \
            --header="━━━━━━━━━━━━━━━ ✦ SESSION-SWITCHER ✦ ━━━━━━━━━━━━━━━" \
            --header-first \
            --ignore-case \
            --delimiter='\t' \
            --with-nth=4 \
            --color="header:italic" \
            --info=hidden \
            --input-border=rounded \
            --preview-border=rounded \
            --preview-window=right:50%:wrap \
            --preview="tmux list-windows -t {1}" \
            --layout=reverse |
        awk -F'\t' '{print $1}'
)

if [[ -z $selected_session ]]; then
    exit 0
fi

if [[ -n "$selected_session" ]]; then
    tmux switch-client -t "$selected_session"
fi
