#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

switcher_key="$(tmux show-option -gqv "@session_switcher_key")"
creator_key="$(tmux show-option -gqv "@session_create_key")"
custom_switcher_header="$(tmux show-option -gqv "@session_switcher_header")"

if [[ -z "$switcher_key" ]]; then
    switcher_key="$(tmux show-option -gqv "@session_manager_key")"
fi

if [[ -z "$creator_key" ]]; then
    creator_key="$(tmux show-option -gqv "@session_creator_key")"
fi

switcher_key="${switcher_key:-s}"
creator_key="${creator_key:-j}"

if [[ -n "$custom_switcher_header" ]]; then
    header_text="$custom_switcher_header"
else
    header_text="󰆍 Session Switcher | Prefix+$creator_key: creator | Ctrl-O: new | Ctrl-D: delete"
fi

selected_session=$(
    bash "$script_dir/session-list" |
        fzf --reverse \
            --prompt="-> " \
            --header="$header_text" \
            --header-first \
            --ignore-case \
            --delimiter='\t' \
            --with-nth=4 \
            --color="header:italic,border:#908caa,pointer:#9ccfd8,marker:#eb6f92" \
            --border=rounded \
            --info=hidden \
            --input-border=rounded \
            --preview-border=rounded \
            --preview-window=right:50%:wrap \
            --preview="tmux list-windows -t {1}" \
            --preview="bash $script_dir/session-preview {1}" \
            --bind="ctrl-o:become(bash '$script_dir/sessionizer')" \
            --bind="ctrl-d:execute-silent(bash '$script_dir/delete-session' {1})+reload(bash '$script_dir/session-list')" \
            --bind="ctrl-l:execute-silent(bash -c 'tmux select-window -t {1} -n')+reload(bash '$script_dir/session-preview' {1})" \
            --bind="ctrl-h:execute-silent(bash -c 'tmux select-window -t {1} -p')+reload(bash '$script_dir/session-preview' {1})" \
            --layout=reverse |
        awk -F'\t' '{print $1}'
)

if [[ -z $selected_session ]]; then
    exit 0
fi

if [[ -n "$selected_session" ]]; then
    tmux switch-client -t "$selected_session"
fi
